# configuration file for dotnet-releaser
profile = "custom"
[msbuild]
project = "Haraltd.sln"
[msbuild.properties]
PublishReadyToRun = false
SkipCopyingSymbolsToOutputDirectory = true
CopyOutputSymbolsToOutputDirectory = false
DebugSymbols = false
DebugType = "None"
DebuggerSupport = false
[github]
user = "bluetuith-org"
repo = "haraltd"
version_prefix = "v"
branches = ["master"]
[[pack]]
rid = ["win-x64", "win-x86", "win-arm64"]
kinds = ["zip"]
[nuget]
publish = false
[scoop]
publish = false
[changelog]
path = "../CHANGELOG.md"
publish = false
